Created basic compute interface
gigabit-clowns/xmipp4-core pull request #77
Opened 2024-11-07 11:49 UTC by oierlauzi

Created the compute interface. This interface enables basic interactions with compute devices, such as GPUs. This includes:

- Querying available device backends (CUDA, host...)
- Querying available devices from each backend (or collectively)
- Query device properties.
- Create command queues for a given device.
- Allocate memory local to a device.
- Transfer data from and to devices asynchronously in queues. Also for unified memory environments data transfers can occur in a zero-copy manner.

2024-11-07 11:50 UTC, oierlauzi commented
I will try to create a couple of implementations of these interfaces (host and CUDA) before marking ready for review

2024-11-08 18:09 UTC, MartinSalinas98 commented on include/xmipp4/core/compute/device_index.hpp
> +    void set_device_id(std::size_t device_id) noexcept;
Remove setter: not needed

2024-11-08 18:09 UTC, MartinSalinas98 commented on include/xmipp4/core/compute/device_index.hpp
> +    void set_backend_name(Str &&backend_name);
Remove setter: not needed

2024-11-08 18:45 UTC, Ratolon submitted a review, later dismissed
Not much to say, looks like a complete enough version for a first compute backend onto which build. I'd say approve but @MartinSalinas98 please di algo.

2024-11-08 19:38 UTC, MartinSalinas98 requested changes

2024-11-08 19:38 UTC, MartinSalinas98 commented on include/xmipp4/core/compute/numerical_type.inl
> +    default: return 0;
Change magic numbers by sizeof when possible.

2024-11-08 19:38 UTC, MartinSalinas98 commented on include/xmipp4/core/system/host.hpp
> +
Add `get_available_system_memory` method. Makes sense to have that information

2024-11-08 19:38 UTC, MartinSalinas98 commented on include/xmipp4/core/compute/device_properties.hpp
> +
Add method `get_available_memory`

2024-11-08 19:38 UTC, MartinSalinas98 commented on src/system/host.cpp
> +
`get_available_system_memory`

2024-11-08 19:38 UTC, MartinSalinas98 commented on tests/unitary/src/compute/test_device_index.cpp
> +}
Remove setter

2024-11-08 19:38 UTC, MartinSalinas98 commented on tests/unitary/src/compute/test_device_index.cpp
> +}
Remove setter

2024-11-08 20:19 UTC, oierlauzi commented on include/xmipp4/core/compute/device_index.inl
> +}
Done

2024-11-08 20:19 UTC, oierlauzi commented on include/xmipp4/core/compute/device_index.inl
> +}
Done

2024-11-08 21:02 UTC, MartinSalinas98 approved these changes

2024-11-08 21:07 UTC, MartinSalinas98 requested changes
Fix Windows warning:
```
error C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS
```

2024-11-08 21:14 UTC, MartinSalinas98 approved these changes

2024-11-08 21:16 UTC, merged